import os

from .base import (
    AUTH_PASSWORD_VALIDATORS,
    BASE_DIR,
    DATABASES,
    DEBUG,
    DEFAULT_AUTO_FIELD,
    INSTALLED_APPS,
    LANGUAGE_CODE,
    MIDDLEWARE,
    ROOT_URLCONF,
    TEMPLATES,
    TIME_ZONE,
    USE_I18N,
    USE_L10N,
    USE_TZ,
    WSGI_APPLICATION,
    ASGI_APPLICATION,
    CHANNEL_LAYERS
)

__all__ = [
    "BASE_DIR",
    "DEBUG",
    "INSTALLED_APPS",
    "MIDDLEWARE",
    "ROOT_URLCONF",
    "TEMPLATES",
    "WSGI_APPLICATION",
    "DATABASES",
    "AUTH_PASSWORD_VALIDATORS",
    "LANGUAGE_CODE",
    "TIME_ZONE",
    "USE_I18N",
    "USE_L10N",
    "USE_TZ",
    "DEFAULT_AUTO_FIELD",
    "ASGI_APPLICATION",
    "CHANNEL_LAYERS"
]


SECURE_HSTS_SECONDS = 60
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

SECURE_SSL_REDIRECT = True

SECRET_KEY = os.environ.get("SECRET_KEY", "_v#lx*6%3t_n@vxkk_+&%7jg2z&6peq(a_v=%r(n8l#k55%k8$")

SESSION_COOKIE_SECURE = True

CSRF_COOKIE_SECURE = True

ALLOWED_HOSTS = os.environ["ALLOWED_HOSTS"].split(",")

SECURE_HSTS_PRELOAD = True
